// Team members data shared between components
export const teamMembers = [
    {
        id: 1,
        name: 'Emily Johnson',
        email: 'emily@gptnexus.com',
        role: 'Admin',
        department: 'Product',
        position: 'Product Manager',
        joined: 'Mar 15, 2022',
        lastActive: 'Apr 2, 2023',
        status: 'Active',
        assignedGPTs: 8
    },
    {
        id: 2,
        name: 'Michael Chen',
        email: 'michael@gptnexus.com',
        role: 'Employee',
        department: 'Engineering',
        position: 'Senior Developer',
        joined: 'Jan 10, 2022',
        lastActive: 'Apr 3, 2023',
        status: 'Active',
        assignedGPTs: 12
    },
    {
        id: 3,
        name: 'Sophia Martinez',
        email: 'sophia@gptnexus.com',
        role: 'Employee',
        department: 'Design',
        position: 'UI/UX Designer',
        joined: 'May 22, 2022',
        lastActive: 'Apr 1, 2023',
        status: 'Active',
        assignedGPTs: 6
    },
    {
        id: 4,
        name: 'David Wilson',
        email: 'david@gptnexus.com',
        role: 'Employee',
        department: 'Marketing',
        position: 'Marketing Specialist',
        joined: 'Jul 8, 2022',
        lastActive: 'Mar 28, 2023',
        status: 'Inactive',
        assignedGPTs: 4
    },
    {
        id: 5,
        name: 'Sarah Rodriguez',
        email: 'sarah@gptnexus.com',
        role: 'Employee',
        department: 'Sales',
        position: 'Account Executive',
        joined: 'Feb 15, 2022',
        lastActive: 'Apr 5, 2023',
        status: 'Active',
        assignedGPTs: 7
    },
    {
        id: 6,
        name: 'James Kim',
        email: 'james@gptnexus.com',
        role: 'Admin',
        department: 'Engineering',
        position: 'CTO',
        joined: 'Jan 5, 2022',
        lastActive: 'Apr 3, 2023',
        status: 'Active',
        assignedGPTs: 15
    },
    {
        id: 7,
        name: 'Olivia Wang',
        email: 'olivia@gptnexus.com',
        role: 'Employee',
        department: 'Design',
        position: 'Senior Designer',
        joined: 'Mar 20, 2022',
        lastActive: 'Apr 4, 2023',
        status: 'Active',
        assignedGPTs: 9
    },
    {
        id: 8,
        name: 'Robert Brown',
        email: 'robert@gptnexus.com',
        role: 'Employee',
        department: 'Product',
        position: 'Product Owner',
        joined: 'Feb 12, 2022',
        lastActive: 'Mar 30, 2023',
        status: 'Inactive',
        assignedGPTs: 5
    },
    {
        id: 9,
        name: 'Emma Davis',
        email: 'emma@gptnexus.com',
        role: 'Employee',
        department: 'Marketing',
        position: 'Content Writer',
        joined: 'Apr 5, 2022',
        lastActive: 'Apr 2, 2023',
        status: 'Active',
        assignedGPTs: 3
    },
    {
        id: 10,
        name: 'Daniel Lee',
        email: 'daniel@gptnexus.com',
        role: 'Employee',
        department: 'Engineering',
        position: 'Frontend Developer',
        joined: 'Jan 18, 2022',
        lastActive: 'Apr 1, 2023',
        status: 'Active',
        assignedGPTs: 8
    },
    {
        id: 11,
        name: 'Isabella Garcia',
        email: 'isabella@gptnexus.com',
        role: 'Employee',
        department: 'Customer Support',
        position: 'Support Lead',
        joined: 'Mar 1, 2022',
        lastActive: 'Mar 29, 2023',
        status: 'Inactive',
        assignedGPTs: 6
    },
    {
        id: 12,
        name: 'Alexander Smith',
        email: 'alex@gptnexus.com',
        role: 'Employee',
        department: 'Sales',
        position: 'Sales Manager',
        joined: 'Feb 8, 2022',
        lastActive: 'Apr 3, 2023',
        status: 'Active',
        assignedGPTs: 11
    }
]; 